#!/usr/bin/env python3
"""generate_agents_md.py — Generates AGENTS.md from analyze_repo.sh output via stdin."""

import sys
import os
import argparse
from datetime import date


def parse_input(lines):
    """Parse structured output from analyze_repo.sh."""
    data = {
        "project_name": "",
        "structure": [],
        "languages": {},
        "frameworks": [],
        "conventions": [],
    }

    section = None
    for line in lines:
        line = line.strip()
        if not line:
            continue

        if line.startswith("PROJECT_NAME="):
            data["project_name"] = line.split("=", 1)[1]
        elif line == "---STRUCTURE_START---":
            section = "structure"
        elif line == "---STRUCTURE_END---":
            section = None
        elif line == "---LANGUAGES_START---":
            section = "languages"
        elif line == "---LANGUAGES_END---":
            section = None
        elif line == "---FRAMEWORKS_START---":
            section = "frameworks"
        elif line == "---FRAMEWORKS_END---":
            section = None
        elif line == "---CONVENTIONS_START---":
            section = "conventions"
        elif line == "---CONVENTIONS_END---":
            section = None
        elif line.startswith("Analyzed:"):
            continue  # Summary line, skip
        elif section == "structure":
            data["structure"].append(line)
        elif section == "languages":
            if "=" in line:
                lang, count = line.split("=", 1)
                data["languages"][lang] = int(count)
        elif section == "frameworks":
            data["frameworks"].append(line)
        elif section == "conventions":
            data["conventions"].append(line)

    return data


def build_directory_tree(paths):
    """Build a simplified directory tree from paths."""
    if not paths:
        return "No directories found."

    # Get the root and normalize
    root = paths[0] if paths else "."
    lines = []
    for p in paths[1:]:  # Skip root
        # Make relative to root
        rel = os.path.relpath(p, root)
        if rel == ".":
            continue
        depth = rel.count(os.sep)
        name = os.path.basename(rel)
        prefix = "│   " * depth + "├── " if depth > 0 else "├── "
        lines.append(f"{prefix}{name}/")

    return "\n".join(lines) if lines else "Flat structure (no subdirectories)"


def generate_agents_md(data):
    """Generate AGENTS.md content from parsed data."""
    project_name = data["project_name"] or "Project"
    today = date.today().isoformat()

    # Sort languages by file count (descending)
    sorted_langs = sorted(data["languages"].items(), key=lambda x: x[1], reverse=True)

    # Build tech stack table
    tech_rows = []
    if sorted_langs:
        primary_lang = sorted_langs[0][0]
        tech_rows.append(f"| Primary Language | {primary_lang} |")
        if len(sorted_langs) > 1:
            others = ", ".join(f"{lang} ({count})" for lang, count in sorted_langs[1:])
            tech_rows.append(f"| Other Languages | {others} |")
    for fw in data["frameworks"]:
        name = fw.split("(")[0].strip()
        tech_rows.append(f"| Framework/Tool | {name} |")

    tech_table = "\n".join(tech_rows) if tech_rows else "| - | No specific tech stack detected |"

    # Build conventions list
    conv_items = []
    for c in data["conventions"]:
        conv_items.append(f"- {c}")
    if not conv_items:
        conv_items.append("- No specific conventions detected")

    # Build directory tree
    tree = build_directory_tree(data["structure"])

    content = f"""# {project_name}

> Auto-generated by agents-md-gen skill on {today}

## Project Overview

This is the **{project_name}** project. It contains {sum(data['languages'].values())} source files across {len(data['languages'])} detected languages.

## Directory Structure

```
{project_name}/
{tree}
```

## Tech Stack

| Category | Technology |
|----------|-----------|
{tech_table}

## Conventions

{chr(10).join(conv_items)}

## Getting Started

1. Clone this repository
2. Review the directory structure above
3. Check the Tech Stack table for required tools
4. Follow any framework-specific setup (see Conventions)
"""
    return content


def main():
    parser = argparse.ArgumentParser(description="Generate AGENTS.md from analyze_repo.sh output")
    parser.add_argument("--output", "-o", default=os.path.join(os.getcwd(), "AGENTS.md"),
                        help="Output file path (default: ./AGENTS.md)")
    parser.add_argument("--force", "-f", action="store_true",
                        help="Overwrite existing AGENTS.md without warning")
    args = parser.parse_args()

    lines = sys.stdin.readlines()
    if not lines:
        print("Error: No input received. Run: bash analyze_repo.sh | python generate_agents_md.py", file=sys.stderr)
        sys.exit(1)

    # Overwrite protection
    if os.path.exists(args.output) and not args.force:
        print(f"Error: {args.output} already exists. Use --force to overwrite.", file=sys.stderr)
        sys.exit(1)

    data = parse_input(lines)
    content = generate_agents_md(data)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(content)

    line_count = content.count("\n")
    print(f"AGENTS.md created (5 sections, {line_count} lines)")


if __name__ == "__main__":
    main()
